import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/molecols/sliders/Header";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Frasma - web3 Onfire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex justify-center text-6xl p-6 items-center">
        <Header />
      </div>
    </div>
  );
}
