import Head from "next/head";
import Image from "next/image";
import SliderOne from "../components/molecols/sliders/Header";
import Footer from "../components/molecols/footer/Footer";
import ShortDescription from "../components/molecols/shortDescription/ShortDescription";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frasma - Food web3 Onfire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SliderOne label="Food on Web3 is on fire " />
      <ShortDescription />
    </>
  );
}
